-- Run once in Supabase SQL Editor for channel media, memes, and the trade block.

alter table public.feed_posts
  add column if not exists channel text not null default 'league-feed',
  add column if not exists media_url text,
  add column if not exists media_type text,
  add column if not exists media_alt text;

alter table public.feed_posts drop constraint if exists feed_posts_body_check;
alter table public.feed_posts drop constraint if exists feed_posts_channel_check;
alter table public.feed_posts
  add constraint feed_posts_body_check
    check (char_length(coalesce(body, '')) <= 1500 and (char_length(trim(coalesce(body, ''))) > 0 or media_url is not null)),
  add constraint feed_posts_channel_check
    check (channel in ('league-feed', 'trade-talk', 'memes'));

create table if not exists public.trade_block_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_team_id text,
  author_team_name text,
  player_name text not null check (char_length(player_name) between 1 and 100),
  position text,
  nfl_team text,
  note text check (char_length(coalesce(note, '')) <= 500),
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.trade_interests (
  trade_item_id bigint not null references public.trade_block_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (trade_item_id, user_id)
);

alter table public.trade_block_items enable row level security;
alter table public.trade_interests enable row level security;

drop policy if exists "league members read trade block" on public.trade_block_items;
create policy "league members read trade block" on public.trade_block_items for select
  using (public.is_allowed_league_member());
drop policy if exists "league members add trade block" on public.trade_block_items;
create policy "league members add trade block" on public.trade_block_items for insert
  with check (public.is_allowed_league_member() and auth.uid() = user_id);
drop policy if exists "owners update trade block" on public.trade_block_items;
create policy "owners update trade block" on public.trade_block_items for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "league members read trade interest" on public.trade_interests;
create policy "league members read trade interest" on public.trade_interests for select
  using (public.is_allowed_league_member());
drop policy if exists "league members add trade interest" on public.trade_interests;
create policy "league members add trade interest" on public.trade_interests for insert
  with check (public.is_allowed_league_member() and auth.uid() = user_id);
drop policy if exists "owners remove trade interest" on public.trade_interests;
create policy "owners remove trade interest" on public.trade_interests for delete
  using (auth.uid() = user_id);

grant select, insert, update on public.trade_block_items to authenticated;
grant select, insert, delete on public.trade_interests to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('channel-media', 'channel-media', true, 8388608, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "members view channel media" on storage.objects;
create policy "members view channel media" on storage.objects for select
  using (bucket_id = 'channel-media' and public.is_allowed_league_member());
drop policy if exists "members upload own channel media" on storage.objects;
create policy "members upload own channel media" on storage.objects for insert
  with check (bucket_id = 'channel-media' and public.is_allowed_league_member() and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "members update own channel media" on storage.objects;
create policy "members update own channel media" on storage.objects for update
  using (bucket_id = 'channel-media' and owner_id = auth.uid()::text)
  with check (bucket_id = 'channel-media' and owner_id = auth.uid()::text);
drop policy if exists "members delete own channel media" on storage.objects;
create policy "members delete own channel media" on storage.objects for delete
  using (bucket_id = 'channel-media' and owner_id = auth.uid()::text);

notify pgrst, 'reload schema';
