-- Row Fast Eat Ass Season 10 · Power Rankings conversations
-- Run this once in Supabase > SQL Editor if the main schema was installed
-- before the sample Power Rankings page was added.

create table if not exists public.power_ranking_comments (
  id bigint generated by default as identity primary key,
  ranking_key text not null check (char_length(ranking_key) between 1 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar text,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.power_ranking_reactions (
  id bigint generated by default as identity primary key,
  ranking_key text not null check (char_length(ranking_key) between 1 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍', '❤️', '😂', '🔥', '🏈', '👀')),
  created_at timestamptz not null default now(),
  unique (ranking_key, user_id, emoji)
);

create index if not exists power_ranking_comments_key_idx
  on public.power_ranking_comments(ranking_key, created_at);
create index if not exists power_ranking_reactions_key_idx
  on public.power_ranking_reactions(ranking_key);

alter table public.power_ranking_comments enable row level security;
alter table public.power_ranking_reactions enable row level security;

drop policy if exists "members read power ranking comments" on public.power_ranking_comments;
create policy "members read power ranking comments" on public.power_ranking_comments for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "members create power ranking comments" on public.power_ranking_comments;
create policy "members create power ranking comments" on public.power_ranking_comments for insert to authenticated
  with check (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "authors delete power ranking comments" on public.power_ranking_comments;
create policy "authors delete power ranking comments" on public.power_ranking_comments for delete to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());

drop policy if exists "members read power ranking reactions" on public.power_ranking_reactions;
create policy "members read power ranking reactions" on public.power_ranking_reactions for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "members create power ranking reactions" on public.power_ranking_reactions;
create policy "members create power ranking reactions" on public.power_ranking_reactions for insert to authenticated
  with check (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "members remove power ranking reactions" on public.power_ranking_reactions;
create policy "members remove power ranking reactions" on public.power_ranking_reactions for delete to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());

create or replace function public.stamp_comment_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare member public.profiles%rowtype;
begin
  select * into member from public.profiles where id = new.user_id;
  new.author_name := member.display_name;
  new.author_avatar := member.avatar_url;
  return new;
end;
$$;

drop trigger if exists stamp_power_ranking_comment_author on public.power_ranking_comments;
create trigger stamp_power_ranking_comment_author
  before insert on public.power_ranking_comments
  for each row execute procedure public.stamp_comment_author();

-- Make the newly-created tables available to Supabase's REST API immediately.
grant select, insert, delete on public.power_ranking_comments to authenticated;
grant select, insert, delete on public.power_ranking_reactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
notify pgrst, 'reload schema';
