-- Row Fast Eat Ass Season 10 · league feed
-- Run this entire file once in Supabase > SQL Editor.

create table if not exists public.allowed_members (
  email text primary key,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null,
  avatar_url text,
  team_id integer check (team_id between 1 and 12),
  team_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feed_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar text,
  author_team_id integer,
  author_team_name text,
  body text not null check (char_length(body) between 1 and 1500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feed_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar text,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.feed_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍', '❤️', '😂', '🔥', '🏈', '👀')),
  created_at timestamptz not null default now(),
  unique (post_id, user_id, emoji)
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-images',
  'profile-images',
  true,
  4194304,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create index if not exists feed_posts_created_at_idx on public.feed_posts(created_at desc);
create index if not exists feed_comments_post_id_idx on public.feed_comments(post_id, created_at);
create index if not exists feed_reactions_post_id_idx on public.feed_reactions(post_id);

alter table public.allowed_members enable row level security;
alter table public.profiles enable row level security;
alter table public.feed_posts enable row level security;
alter table public.feed_comments enable row level security;
alter table public.feed_reactions enable row level security;

create or replace function public.is_allowed_league_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    not exists (select 1 from public.allowed_members where active = true)
    or exists (
      select 1 from public.allowed_members
      where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
        and active = true
    );
$$;

grant execute on function public.is_allowed_league_member() to authenticated;

drop policy if exists "members read profiles" on public.profiles;
create policy "members read profiles" on public.profiles for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "users create own profile" on public.profiles;
create policy "users create own profile" on public.profiles for insert to authenticated
  with check (auth.uid() = id and public.is_allowed_league_member());
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated
  using (auth.uid() = id and public.is_allowed_league_member())
  with check (auth.uid() = id and public.is_allowed_league_member());

drop policy if exists "members read posts" on public.feed_posts;
create policy "members read posts" on public.feed_posts for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "members create posts" on public.feed_posts;
create policy "members create posts" on public.feed_posts for insert to authenticated
  with check (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "authors update posts" on public.feed_posts;
create policy "authors update posts" on public.feed_posts for update to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "authors delete posts" on public.feed_posts;
create policy "authors delete posts" on public.feed_posts for delete to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());

drop policy if exists "members read comments" on public.feed_comments;
create policy "members read comments" on public.feed_comments for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "members create comments" on public.feed_comments;
create policy "members create comments" on public.feed_comments for insert to authenticated
  with check (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "authors delete comments" on public.feed_comments;
create policy "authors delete comments" on public.feed_comments for delete to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());

drop policy if exists "members read reactions" on public.feed_reactions;
create policy "members read reactions" on public.feed_reactions for select to authenticated
  using (public.is_allowed_league_member());
drop policy if exists "members create reactions" on public.feed_reactions;
create policy "members create reactions" on public.feed_reactions for insert to authenticated
  with check (auth.uid() = user_id and public.is_allowed_league_member());
drop policy if exists "members remove reactions" on public.feed_reactions;
create policy "members remove reactions" on public.feed_reactions for delete to authenticated
  using (auth.uid() = user_id and public.is_allowed_league_member());

drop policy if exists "members upload own profile image" on storage.objects;
create policy "members upload own profile image" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'profile-images'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.is_allowed_league_member()
  );
drop policy if exists "members read own profile image" on storage.objects;
create policy "members read own profile image" on storage.objects for select to authenticated
  using (
    bucket_id = 'profile-images'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.is_allowed_league_member()
  );
drop policy if exists "members update own profile image" on storage.objects;
create policy "members update own profile image" on storage.objects for update to authenticated
  using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (
    bucket_id = 'profile-images'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.is_allowed_league_member()
  );
drop policy if exists "members delete own profile image" on storage.objects;
create policy "members delete own profile image" on storage.objects for delete to authenticated
  using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, 'League member'), '@', 1)),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.stamp_post_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare member public.profiles%rowtype;
begin
  select * into member from public.profiles where id = new.user_id;
  new.author_name := member.display_name;
  new.author_avatar := member.avatar_url;
  new.author_team_id := member.team_id;
  new.author_team_name := member.team_name;
  return new;
end;
$$;

drop trigger if exists stamp_feed_post_author on public.feed_posts;
create trigger stamp_feed_post_author
  before insert or update on public.feed_posts
  for each row execute procedure public.stamp_post_author();

create or replace function public.stamp_comment_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare member public.profiles%rowtype;
begin
  select * into member from public.profiles where id = new.user_id;
  new.author_name := member.display_name;
  new.author_avatar := member.avatar_url;
  return new;
end;
$$;

drop trigger if exists stamp_feed_comment_author on public.feed_comments;
create trigger stamp_feed_comment_author
  before insert on public.feed_comments
  for each row execute procedure public.stamp_comment_author();

-- Before launch, insert the owners' Google account emails. Once this table has
-- at least one active row, all other Google accounts are denied by row security.
-- insert into public.allowed_members (email) values
--   ('owner1@gmail.com'),
--   ('owner2@gmail.com');
